# Generated by Django 3.2.3 on 2021-06-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
